### ISSUE TITLE
Javascript errors after fresh install

### ISSUE THREAD

**Issue by arifje** [mostlyserious/craft-promptly#4]
Installed the plugin, enabled some description fields (type: Redactor), getting this JS error:

![Screenshot 2024-01-10 at 09 29 41](https://github.com/mostlyserious/craft-promptly/assets/1286410/acd49752-a989-4382-ab5b-a72fd39a1915)

As a result the dialog keeps spinning and not showing anything.

Running Craft Pro 4.5.12

**Comment by corneliusio** [comment]
Very odd. Would you mind clearing out your `/storage/log` directory, repeating this, and posting a copy of your logs here? Please feel free to remove anything sensitive such as directory paths or user data. If you'd rather not post here, you can email to cornelius [at] mostlyserious.io

**Comment by arifje** [comment]
Sorry for the late reply. Here's more info. It's an SQL related error.

![Screenshot 2024-02-04 at 14 46 35](https://github.com/mostlyserious/craft-promptly/assets/1286410/72b4414d-f540-485f-8d5a-b7a3962ba272)

ps. after installing the plugin I can't find any tables related to the plugin, doesn't seem to be created

**Comment by corneliusio** [comment]
@arifje Your good, sorry for the delay on my end as well. I plan on getting a hotfix out for this asap—I've been buried in client work for the last few weeks now and it's unfortunately come out of time on fixing this. Thanks for the details!

**Comment by corneliusio** [comment]
@arifje This issue should be fixed in the most recent update—v1.2.4.

Give it a shot and let me know if you run into any issues!

**Comment by arifje** [comment]
Reinstalled the plugin, still getting the errors:

![Screenshot 2024-04-11 at 09 59 11](https://github.com/mostlyserious/craft-promptly/assets/1286410/dcbeb5d2-291a-4d34-a309-7d898692c818)

![Screenshot 2024-04-11 at 09 59 19](https://github.com/mostlyserious/craft-promptly/assets/1286410/4d550113-602a-49ae-9268-04ddfbf3d3f4)

**Comment by bwatabu55** [comment]
I am facing the same issue here, also tried to use 1.2.4 version

**Comment by john-henry** [comment]
Same here. No tables created on installation
